/**
 * Turkish translations for class/race feature descriptions, keyed by SRD feature index.
 * Filled in incrementally — a feature missing here just falls back to the English SRD text.
 * 2014 and 2024 often use different indices for the "same" feature (and sometimes the same
 * index, e.g. Barbarian Unarmored Defense), so both are listed separately where they differ.
 */
export const FEATURE_DESCRIPTIONS_TR: Record<string, string> = {
  rage:
    "Savaşta ilkel bir vahşetle dövüşürsün. Turunda bir bonus aksiyonla öfkeye girebilirsin. Öfkeliyken, ağır zırh giymiyorsan şu avantajları kazanırsın: Kuvvet kontrollerinde ve Kuvvet kurtarma zarlarında avantajlı olursun; Kuvvet kullanarak yaptığın yakın dövüş silah saldırılarında hasar zarına +2 bonus eklersin (bu bonus seviye arttıkça artar); ezici, delici ve kesici hasara karşı direnç kazanırsın. Büyü kullanabiliyorsan öfkeliyken büyü okuyamaz veya konsantre olamazsın. Öfken 1 dakika sürer; bilinçsiz düşersen veya son turundan beri düşman bir yaratığa saldırmadıysan ya da hasar almadıysan erken sona erer. Öfkeni turunda bir bonus aksiyonla da bitirebilirsin. Barbar seviyene göre maksimum öfke sayısına ulaştıysan, tekrar öfkelenebilmek için bir uzun dinlenme almalısın. 1. seviyede 2 kez, 3. seviyede 3 kez, 6. seviyede 4 kez, 12. seviyede 5 kez ve 17. seviyede 6 kez öfkelenebilirsin.",
  "barbarian-rage":
    "Öfke adı verilen ilkel bir güçle kendini doldurabilirsin; bu güç sana olağanüstü kuvvet ve dayanıklılık kazandırır. Ağır zırh giymiyorsan bir bonus aksiyonla öfkeye girebilirsin. Barbar seviyene göre Barbar Özellikleri tablosundaki Öfke sütununda belirtilen sayıda öfkeye girebilirsin; harcanan bir kullanımı bir kısa dinlenmede, hepsini ise bir uzun dinlenmede geri kazanırsın. Öfke aktifken: ezici, delici ve kesici hasara direnç kazanırsın; bir silah veya silahsız vuruşla Kuvvet kullanarak yaptığın saldırılarda hasara bonus eklersin (seviye arttıkça artar); Kuvvet kontrol ve kurtarma zarlarında avantajlısın; konsantre olamaz ve büyü okuyamazsın. Öfke, sıradaki turunun sonuna kadar sürer; ağır zırh giyersen ya da Etkisiz Hale Getirilmiş (Incapacitated) durumuna girersen erken sona erer. Bir düşmana saldırı zarı atarak, bir düşmanı kurtarma zarına zorlayarak ya da bir bonus aksiyon harcayarak öfkeni bir tur daha uzatabilirsin; bu şekilde toplamda 10 dakikaya kadar sürdürebilirsin.",
  "barbarian-unarmored-defense":
    "Herhangi bir zırh giymiyorken Zırh Sınıfın 10 + Çeviklik değiştiricin + Dayanıklılık değiştiricine eşittir. Bir kalkan kullanırken de bu avantajı korursun.",
  "lay-on-hands":
    "Kutsanmış dokunuşun yaraları iyileştirebilir. Uzun dinlenmede yenilenen bir iyileştirme gücü havuzun vardır. Bu havuzla, toplamda paladin seviyen × 5 kadar can puanı geri kazandırabilirsin. Bir aksiyonla bir yaratığa dokunup havuzundan güç çekerek, havuzda kalan miktara kadar can puanı geri verebilirsin. Alternatif olarak, havuzundan 5 can puanı harcayarak hedefteki bir hastalığı iyileştirebilir ya da bir zehri etkisiz hale getirebilirsin; her biri için ayrı ayrı can puanı harcayarak birden fazla hastalık/zehri aynı kullanımda giderebilirsin. Bu özelliğin yaşayan ölüler ve yapay canlılar üzerinde etkisi yoktur.",
  "paladin-lay-on-hands":
    "Kutsanmış dokunuşun yaraları iyileştirebilir. Uzun dinlenmede yenilenen bir iyileştirme gücü havuzun vardır; bu havuzla toplamda paladin seviyenin beş katı kadar can puanı geri kazandırabilirsin. Bir bonus aksiyonla bir yaratığa (kendin dahil) dokunup havuzdan çektiğin güçle, havuzda kalan miktara kadar can puanı verebilirsin. Ayrıca havuzdan 5 can puanı harcayarak hedefteki Zehirlenmiş (Poisoned) durumunu giderebilirsin; bu can puanları ayrıca iyileştirme sağlamaz.",
  "divine-smite":
    "2. seviyeden itibaren, bir yaratığa yakın dövüş silah saldırısıyla vurduğunda bir büyü yuvası harcayarak silahın hasarına ek olarak radyan hasar verebilirsin. Ek hasar 1. seviye bir yuva için 2d8'dir; 1. seviyenin üzerindeki her yuva seviyesi için 1d8 daha eklenir, en fazla 5d8'e kadar. Hedef yaşayan ölü ya da iblis (fiend) ise hasar 1d8 daha artar.",
  "paladin-paladins-smite":
    "Divine Smite büyüsü her zaman hazırlanmış sayılır. Ayrıca bu büyüyü bir büyü yuvası harcamadan okuyabilirsin; ancak bunu tekrar yapabilmek için önce bir uzun dinlenme almalısın.",
  "wild-shape-cr-1-4-or-below-no-flying-or-swim-speed":
    "2. seviyeden itibaren, aksiyonunu kullanarak daha önce gördüğün bir canavarın şekline büyüsel olarak bürünebilirsin. Bu özelliği iki kez kullanabilirsin; harcanan kullanımları bir kısa ya da uzun dinlenmede geri kazanırsın. Druid seviyen, dönüşebileceğin canavarları belirler — 2. seviyede, uçma ya da yüzme hızı olmayan ve zorluk derecesi (CR) 1/4 veya altında olan herhangi bir canavara dönüşebilirsin. Canavar formunda druid seviyenin yarısı kadar saat (aşağı yuvarlanır) kalabilirsin; bu sürenin sonunda normal formuna dönersin, tabii başka bir kullanım harcamazsan. Bilincini kaybedersen, 0 can puanına düşersen ya da ölürsen otomatik olarak normal formuna dönersin.",
  "druid-wild-shape":
    "Doğanın gücü, bir hayvanın formuna bürünmene olanak tanır. Bir bonus aksiyonla, bu özellik için öğrendiğin bir Canavar formuna dönüşürsün. Druid seviyenin yarısı kadar saat bu formda kalırsın; süre dolana, Wild Shape'i tekrar kullanana, Etkisiz Hale Getirilmiş duruma girene ya da ölene kadar. Bu formu bir bonus aksiyonla erken de bırakabilirsin. Bu özelliği iki kez kullanabilirsin; bir kısa dinlenmede bir kullanım, bir uzun dinlenmede ise tüm kullanımlarını geri kazanırsın. Belirli druid seviyelerine ulaştıkça ek kullanımlar ve daha yüksek zorluk dereceli formlar kazanırsın.",
};
